name       : haskell-asn1-types
version    : 0.3.4
release    : 3
source     :
    - https://hackage.haskell.org/package/asn1-types-0.3.4/asn1-types-0.3.4.tar.gz : 78ee92a251379298ca820fa53edbf4b33c539b9fcd887c86f520c30e3b4e21a8
license    : BSD-3-Clause
component  : programming.haskell
summary    : ASN.1 standard types
description: |
    ASN.1 standard types
builddeps  :
    - haskell-cabal-install
    - haskell-hourglass-devel
    - haskell-memory-devel
rundeps    :
    - devel:
        - haskell-hourglass-devel
        - haskell-memory-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
