name       : haskell-asn1-types
version    : 0.3.2
release    : 2
source     :
    - http://hackage.haskell.org/package/asn1-types-0.3.2/asn1-types-0.3.2.tar.gz : 0c571fff4a10559c6a630d4851ba3cdf1d558185ce3dcfca1136f9883d647217
license    : BSD-3-Clause
component  : programming.haskell
summary    : ASN.1 standard types
description: "ASN.1 standard types \n"
builddeps  :
    - haskell-cabal-install
    - haskell-hourglass
    - haskell-memory
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
